#!/usr/bin/env php
<?php

use yii\console\Application;
use yii\console\controllers\MigrateController;
use yii\helpers\ArrayHelper;
use Wearesho\Evrotel;
use Wearesho\Yii\Filesystem;

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

require(__DIR__ . '/tests/autoload.php');

$configPath = Yii::getAlias('@configFile');
$testsConfig = is_file($configPath) ? require $configPath : [];
$config = [
    'controllerMap' => [
        'migrate' => [
            'class' => MigrateController::class,
            'migrationNamespaces' => [
                'Wearesho\\Evrotel\\Yii\\Migrations',
            ],
            'migrationPath' => null,
        ],
        'evrotel' => [
            'class' => Evrotel\Yii\Console\Controller::class,
        ],
    ],
    'bootstrap' => [
        'evrotel' => [
            'class' => Evrotel\Yii\Bootstrap::class,
            'console' => null,
        ],
        'fs' => [
            'class' => Filesystem\Bootstrap::class,
            'container' => true,
            'adapters' => [
                'local' => [
                    'class' => Filesystem\Local\Adapter::class,
                    'config' => [
                        'class' => Filesystem\Local\Config::class,
                        'savePath' => '@runtime/tests/output',
                    ],
                ],
            ],
            'config' => [
                'class' => Filesystem\Config::class,
                'adapter' => 'local',
            ],
        ],
    ],
    'container' => [
        'definitions' => [
            GuzzleHttp\ClientInterface::class => GuzzleHttp\Client::class,
        ],
    ],
];

/** @noinspection PhpUnhandledExceptionInspection */
$application = new Application(ArrayHelper::merge($testsConfig, $config));
$exitCode = $application->run();
exit($exitCode);
